TinkerJems.Web2/Pages/AboutMe.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TinkerJems.Web2.Pages
{
    public class AboutMeModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

TinkerJems.Web2/Pages/Blog.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TinkerJems.Core.Models;
using TinkerJems.Web2.Data;
using TinkerJems.Web2.Services;

namespace TinkerJems.Web2.Pages
{
    public class BlogsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public IList<TinkerJemsBlogPost> BlogPosts { get; set; }
        public IList<TinkerJemsBlogPost> sortedPosts { get; set; }

        private readonly IAdviceService _greatAdviceService;

        public TinkerJemsBlogPost BlogPost { get; set; }

        public BlogsModel(ApplicationDbContext context, IAdviceService adviceService)
        {
            _context = context;
            BlogPosts = new List<TinkerJemsBlogPost>();
            sortedPosts = new List<TinkerJemsBlogPost>();
            _greatAdviceService = adviceService;
        }

        private GreatAdvice advice;

        public GreatAdvice Advice
        {
            get { return advice; }
            set { advice = value; }
        }

        public async Task OnGetAsync()
        {
            BlogPosts = await _context.TinkerJemsBlogPost.ToListAsync();
            sortedPosts = BlogPosts.OrderByDescending(o => o.Posted).ToList();
            Advice = await _greatAdviceService.GetAdviceAsync();
        }
    }
}

TinkerJems.Web2/Pages/Blogs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TinkerJems.Core.Models;
using TinkerJems.Web2.Data;

namespace TinkerJems.Web2.Pages
{
    public class BlogsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public IList<TinkerJemsBlogPost> BlogPosts { get; set; }
        public IList<TinkerJemsBlogPost> sortedPosts { get; set; }
        public TinkerJemsBlogPost BlogPost { get; set; }

        public BlogsModel(ApplicationDbContext context)
        {
            _context = context;
            BlogPosts = new List<TinkerJemsBlogPost>();
            sortedPosts = new List<TinkerJemsBlogPost>();
        }
        public async Task OnGetAsync()
        {
            BlogPosts = await _context.TinkerJemsBlogPost.ToListAsync();
            sortedPosts = BlogPosts.OrderByDescending(o => o.Posted).ToList();
        }
    }
}

TinkerJems.Web2/Pages/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting.Internal;
using TinkerJems.Core.Models;

namespace TinkerJems.Web2.Pages
{
    public class CreateModel : PageModel
    {
        private readonly Data.ApplicationDbContext _context;
        private readonly IWebHostEnvironment hostingEnvironment;

        public CreateModel(Data.ApplicationDbContext context, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            this.hostingEnvironment = hostingEnvironment;
        }

        public string[] Images { get; set; }

        [BindProperty]
        public string NewTags { get; set; }
        public IActionResult OnGet()
        {
            var folder = Path.Combine(hostingEnvironment.ContentRootPath, "wwwroot", "Images");
            Images = Directory.GetFiles(folder);
            return Page();
        }

        [BindProperty]
        public JewelryItem JewelryItem { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            JewelryItem.ImageThumbnailUrl = JewelryItem.ImageUrl;
            _context.JewelryItems.Add(JewelryItem);
            await _context.SaveChangesAsync();
           foreach (var tagName in NewTags.Split("\r\n"))
            {
                var tag = await _context.Tags.FirstOrDefaultAsync(t => t.Name == tagName);
                if(tag == null)
                {
                    tag = new Tag { Name = tagName };
                    _context.Tags.Add(tag);
                    await _context.SaveChangesAsync();
                }
                var itemTag = new JewelryItemTag();
                itemTag.JewelryItemId = JewelryItem.Id;
                itemTag.Tag = tag;
                itemTag.TagId = tag.Id;
                _context.ItemTags.Add(itemTag);
                await _context.SaveChangesAsync();
            }
            await _context.SaveChangesAsync();
            return RedirectToPage("./Items");
        }
       
    }
}

TinkerJems.Web2/Pages/CreateBlog.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TinkerJems.Core.Models;
using TinkerJems.Web2.Data;

namespace TinkerJems.Web2.Pages
{
    public class CreateBlogModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment hostEnvironment;

        public CreateBlogModel(Data.ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this.hostEnvironment = hostEnvironment;
        }

        public string[] Images { get; set; }
        public string[] BlogPosts { get; set; }

        public IActionResult OnGet()
        {
            var folder = Path.Combine(hostEnvironment.ContentRootPath, "wwwroot", "Images");
            Images = Directory.GetFiles(folder);
            var postsFolder = Path.Combine(hostEnvironment.ContentRootPath, "wwwroot", "BlogPosts");
            BlogPosts = Directory.GetFiles(postsFolder);

            return Page();
        }

        [BindProperty]
        public TinkerJemsBlogPost BlogPost { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            BlogPost.Posted = DateTime.Now;
            _context.TinkerJemsBlogPost.Add(BlogPost);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Blogs");
        }
    }
}

TinkerJems.Web2/Pages/CreatePost.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TinkerJems.Core.Models;
using TinkerJems.Web2.Data;

namespace TinkerJems.Web2.Pages
{
    public class CreateBlogModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment hostEnvironment;

        public CreateBlogModel(Data.ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this.hostEnvironment = hostEnvironment;
        }

        public string[] Images { get; set; }
        public string[] BlogPosts { get; set; }

        public IActionResult OnGet()
        {
            var folder = Path.Combine(hostEnvironment.ContentRootPath, "wwwroot", "Images");
            Images = Directory.GetFiles(folder);
            var postsFolder = Path.Combine(hostEnvironment.ContentRootPath, "wwwroot", "BlogPosts");
            BlogPosts = Directory.GetFiles(postsFolder);

            return Page();
        }

        [BindProperty]
        public TinkerJemsBlogPost BlogPost { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            BlogPost.Posted = DateTime.Now;
            BlogPost.Slug = MakeFriendly(BlogPost.Title);
            _context.TinkerJemsBlogPost.Add(BlogPost);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Blog");
        }

        public static string MakeFriendly(string text)
        {
            if (text == null) return "";

            const int maxlen = 80;
            int len = text.Length;
            bool prevdash = false;
            var sb = new StringBuilder(len);
            char c;

            for (int i = 0; i < len; i++)
            {
                c = text[i];
                if ((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9'))
                {
                    sb.Append(c);
                    prevdash = false;
                }
                else if (c >= 'A' && c <= 'Z')
                {
                    // tricky way to convert to lowercase
                    sb.Append((char)(c | 32));
                    prevdash = false;
                }
                else if (c == ' ' || c == ',' || c == '.' || c == '/' ||
                    c == '\\' || c == '-' || c == '_' || c == '=')
                {
                    if (!prevdash && sb.Length > 0)
                    {
                        sb.Append('-');
                        prevdash = true;
                    }
                }
                else if ((int)c >= 128)
                {
                    int prevlen = sb.Length;
                    sb.Append(RemapInternationalCharToAscii(c));
                    if (prevlen != sb.Length) prevdash = false;
                }
                if (i == maxlen) break;
            }

            if (prevdash)
                return sb.ToString().Substring(0, sb.Length - 1);
            else
                return sb.ToString();
        }

        public static string RemapInternationalCharToAscii(char c)
        {
            string s = c.ToString().ToLowerInvariant();
            if ("àåáâäãåą".Contains(s))
            {
                return "a";
            }
            else if ("èéêëę".Contains(s))
            {
                return "e";
            }
            else if ("ìíîïı".Contains(s))
            {
                return "i";
            }
            else if ("òóôõöøőð".Contains(s))
            {
                return "o";
            }
            else if ("ùúûüŭů".Contains(s))
            {
                return "u";
            }
            else if ("çćčĉ".Contains(s))
            {
                return "c";
            }
            else if ("żźž".Contains(s))
            {
                return "z";
            }
            else if ("śşšŝ".Contains(s))
            {
                return "s";
            }
            else if ("ñń".Contains(s))
            {
                return "n";
            }
            else if ("ýÿ".Contains(s))
            {
                return "y";
            }
            else if ("ğĝ".Contains(s))
            {
                return "g";
            }
            else if (c == 'ř')
            {
                return "r";
            }
            else if (c == 'ł')
            {
                return "l";
            }
            else if (c == 'đ')
            {
                return "d";
            }
            else if (c == 'ß')
            {
                return "ss";
            }
            else if (c == 'Þ')
            {
                return "th";
            }
            else if (c == 'ĥ')
            {
                return "h";
            }
            else if (c == 'ĵ')
            {
                return "j";
            }
            else
            {
                return "";
            }
        }
    }
}

TinkerJems.Web2/Pages/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TinkerJems.Core.Models;

namespace TinkerJems.Web2.Pages
{
    public class DeleteModel : PageModel
    {
        private readonly TinkerJems.Web2.Data.ApplicationDbContext _context;

        public DeleteModel(TinkerJems.Web2.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public JewelryItem JewelryItem { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            JewelryItem = await _context.JewelryItems.FirstOrDefaultAsync(m => m.Id == id);

            if (JewelryItem == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            JewelryItem = await _context.JewelryItems.FindAsync(id);

            if (JewelryItem != null)
            {
                _context.JewelryItems.Remove(JewelryItem);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Items");
        }
    }
}

TinkerJems.Web2/Pages/DeletePost.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TinkerJems.Core.Models;
using TinkerJems.Web2.Data;

namespace TinkerJems.Web2.Pages
{
    public class DeletePostModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DeletePostModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public TinkerJemsBlogPost BlogPost { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            BlogPost = await _context.TinkerJemsBlogPost.FindAsync(id);

            if (BlogPost == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            BlogPost = await _context.TinkerJemsBlogPost.FindAsync(id);

            if (BlogPost != null)
            {
                _context.TinkerJemsBlogPost.Remove(BlogPost);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Blog");
        }

    }
}

TinkerJems.Web2/Pages/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TinkerJems.Core;
using TinkerJems.Core.Models;
using TinkerJems.Web2.Data;

namespace TinkerJems.Web2.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DetailsModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public JewelryItem JewelryItem { get; set; }

        [BindProperty]
        public string NewTags { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await loadJewelryItem(id);

            if (JewelryItem == null)
            {
                return NotFound();
            }
            return Page();
        }

        private async Task loadJewelryItem(int? id)
        {
            JewelryItem = await _context.JewelryItems
                            .Include(j => j.Tags)
                            .ThenInclude(t => t.Tag)
                            .FirstOrDefaultAsync(m => m.Id == id);
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            foreach (var tagName in NewTags.Split("\r\n"))
            {
                var tag = await _context.Tags.FirstOrDefaultAsync(t => t.Name == tagName);
                if (tag == null)
                {
                    tag = new Tag { Name = tagName };
                    _context.Tags.Add(tag);
                    await _context.SaveChangesAsync();
                }
                JewelryItem = _context.JewelryItems.FirstOrDefault(m => m.Id == id);
                var itemTag = new JewelryItemTag();
                itemTag.JewelryItem = JewelryItem;
                itemTag.JewelryItemId = JewelryItem.Id;
                itemTag.Tag = tag;
                itemTag.TagId = tag.Id;
                _context.ItemTags.Add(itemTag);
                await _context.SaveChangesAsync();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteTagAsync( int jewelryItemId, int tagId)
        {
            var itemTag = await _context.ItemTags.FirstOrDefaultAsync(it => it.JewelryItemId == jewelryItemId && it.TagId == tagId);
            if (itemTag != null)
            {
                _context.ItemTags.Remove(itemTag);
                 await _context.SaveChangesAsync();
                await loadJewelryItem(jewelryItemId);
            }
            return Page();
        } 
    }
}

TinkerJems.Web2/Pages/AboutMe.cshtml
@page
@model TinkerJems.Web2.Pages.AboutMeModel
@{
    ViewData["Title"] = "AboutMe";
}

<div style="display:flex">
    <img src="~/Images/PersonalPic.jpg" width="550" />
    <div style="display:inline; margin-left:2em">
        <h2 style="text-align:center">About Me</h2>
        <hr />
        <p style="font-size:23px; margin-left:1em">
            Hi there! I'm Nettie Graham, creator of Tinker Gems Jewelry! I have always been in love with the arts - music, painting, dancing - and ever since I dug into my sisters pink jewelry box, I've loved creating jewelry!
            As I developed this skill, I realized after a while that I had been finding every excuse possible to give my pieces away; Christmas, birthdays, Valentines, Easter.
            Then, it clicked! I could simply make a page for people to view my jewelry, and possibly buy it.
            It took a lot of work, but it was well worth it! As far as work goes, I teach small girls how to clog.
            I've found that making jewelry making has fit nicely in my schedule between teaching classes, and I want to expand this hobby into something bigger!
            Thank you for visiting my page, welcome to Tinker Gems Jewelry!
        </p>
        <div style="text-align:center; margin-top:2em;">
            <p style="font-size:23px; margin-left:1em">
                Follow me on Instagram!
            </p>
            <a href="https://www.instagram.com/nettie.graham/" class="fa fa-instagram" style="font-size:50px; color: #E1306C; text-decoration:none; border-radius:50%; margin-left:.5em;"></a>
        </div>
    </div>
</div>

TinkerJems.Web2/Pages/Blog.cshtml
@page
@model TinkerJems.Web2.Pages.BlogsModel
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService Authorization
@{
    var canAdd = (await Authorization.AuthorizeAsync(User, SeedData.SecurityPolicy_Add)).Succeeded;
    var canEdit = (await Authorization.AuthorizeAsync(User, SeedData.SecurityPolicy_Edit)).Succeeded;
}
@{
    ViewData["Title"] = "Posts";
}

<h1 style="text-align:center">Tinker Gems Blog</h1>

@*NAVBAR
    <nav class="navbar navbar-expand-lg navbar-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="background-color:#edc7b7; border-radius: .5em; padding:0em;">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item active">
                    <a class="nav-link" asp-page="./Index">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Jewelry
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-page="./Items">All Jewelry</a>
                        <a class="dropdown-item" href="shopRings.html">Rings</a>
                            <a class="dropdown-item" href="shopNecklaces.html">Necklaces</a>
                            <a class="dropdown-item" href="shopEarrings.html">Earrings</a>
                            <a class="dropdown-item" href="shopBracelets.html">Bracelets and Anklets</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" asp-page="./Blog" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Blog
                    </a>
                </li>
                <li class="nav-item">
                    @*<a class="nav-link" href="#aboutMe">About Me</a>
                </li>
            </ul>
        </div>
    </nav>*@

<div style="text-align:center">
    <span style="font-size:large; font-weight:bold;">Daily advice: @Model.Advice.Advice</span>
</div>

<div>
    @foreach (var blog in Model.sortedPosts)
    {
        <a href="/Post/@blog.Slug" style="text-decoration:none">
            <div class="media" style="border:solid; border-width: .5px; border-radius: 5px; margin:1em; background-color:#fffcff; display:block;">
                <article>
                    @if (blog.Image != null)
                    {
                        <img class="mr-3" style="width:200px; height:200px; margin:.5em; vertical-align:middle" src="/Images/@Html.DisplayFor(modelblog => blog.Image)" alt="Post Image">
                    }
                    <div class="media-body" style="display:inline-block; margin:.5em; position:relative; vertical-align:middle;">
                        <h2 class="mt-0"><a href="/Post/@blog.Slug" style="text-decoration:none; color:black">@Html.DisplayFor(modelItem => blog.Title)</a></h2>
                        <p>@blog.Summary</p>
                        <p>
                            By: @Html.DisplayFor(modelblog => blog.Author)
                        </p>
                        <p>
                            @Html.DisplayFor(modelblog => blog.Posted)
                        </p>
                    </div>
                </article>
            </div>
        </a>
        <hr />
    }

</div>

@if (canAdd)
{
    <a asp-page="./CreatePost">
        <button type="button" class="btn btn-outline-info">Create Entry</button>
    </a>
}

TinkerJems.Web2/Pages/Blogs.cshtml
@page
@model TinkerJems.Web2.Pages.BlogsModel
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService Authorization
@{
    var canAdd = (await Authorization.AuthorizeAsync(User, SeedData.SecurityPolicy_Add)).Succeeded;
    var canEdit = (await Authorization.AuthorizeAsync(User, SeedData.SecurityPolicy_Edit)).Succeeded;
}
@{
    ViewData["Title"] = "Posts";
}

<h1>Posts</h1>
<hr/>

<div>    
    @foreach (var blog in Model.sortedPosts)
    {
        <a asp-page="./Post" asp-route-id="@blog.ID" style="text-decoration:none">
            <div class="media" style="border:solid; border-width: .5px; border-radius: 5px; margin:1em; background-color:#fffcff; display:block;">
                <article>
                    @if(blog.Image != null)
                    {
                         <img asp-route-id="@blog.ID" class="mr-3" style="width:200px; height:200px; margin:.5em; vertical-align:middle" src="/Images/@Html.DisplayFor(modelblog => blog.Image)" alt="Post Image">
                    }
                <div class="media-body" style="display:inline-block; margin:.5em; position:relative; vertical-align:middle;">
                    <h2 class="mt-0"><a asp-page="./Post" asp-route-id="@blog.ID" style="text-decoration:none; color:black">@Html.DisplayFor(modelItem => blog.Title)</a></h2>
                    <p asp-route-id="@blog.ID">@blog.Summary</p>
                    <p asp-route-id="@blog.ID">
                        By: @Html.DisplayFor(modelblog => blog.Author)
                    </p>
                    <p asp-route-id="@blog.ID">
                        @Html.DisplayFor(modelblog => blog.Posted)
                    </p>
                </div>
                </article>
            </div>
        </a>
        <hr />
    }
</div>

@if (canAdd)
{
    <a asp-page="./CreateBlog">
        <button type="button" class="btn btn-outline-info">Create Entry</button>
    </a>
}

TinkerJems.Web2/Pages/Details.cshtml
@page
@model TinkerJems.Web2.Pages.DetailsModel
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService Authorization
@{
    var canEdit = (await Authorization.AuthorizeAsync(User, SeedData.SecurityPolicy_Edit)).Succeeded;

}

@{
    ViewData["Title"] = "Details";
}


<h1 class="text-center">@Html.DisplayFor(model => model.JewelryItem.Name)</h1>


<div style="display:flex">
    <div>
        <img src="/Images/@Html.DisplayFor(model => model.JewelryItem.ImageUrl)" alt="image of item" style="width:300px; height:auto; margin:1em; vertical-align:top;" />
        <hr />
        @if (canEdit)
        {
            <div style="margin-left:1em;">
                <h5 style="text-align:center; margin-bottom:0em;">Add Tags</h5>
            </div>
            <form method="post">
                <div class="form-group">
                    <textarea rows="5" cols="45" asp-for="NewTags" placeholder="Add new tags separated by new lines"></textarea>
                </div>
                <div class="form-group">
                    <input type="submit" value="Add Tags" class="btn btn-outline-secondary" />
                </div>
            </form>
        }
    </div>
    <div style="display:inline-block; margin-top:1em; margin-left:2em; vertical-align:top; display:inline-block">
        <dl class="dl-horizontal text-left" style="display:inline-block">
            <dt>
                @Html.DisplayNameFor(model => model.JewelryItem.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.JewelryItem.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.JewelryItem.Price)
            </dt>
            <dd>
                $@Html.DisplayFor(model => model.JewelryItem.Price)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.JewelryItem.LongDescription)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.JewelryItem.LongDescription)
            </dd>
            <dt>
                Tags
            </dt>
            <dd>
                <div class="container" style="padding-left:0px">
                    <ul class="list-group list-group-horizontal" style="list-style-type:none; margin-top:5px">
                        @if (Model.JewelryItem.Tags == null)
                        {
                            <li style="color:darkgrey;">There are no tags for this item</li>
                        }
                        else
                        {
                            foreach (var tagLink in Model.JewelryItem.Tags)
                            {
                                <li class="list-group-item" style="margin-right:5px; height:max-content; width:max-content; padding:5px; display:inherit">

                                    <a asp-page="./SelectedTag" asp-route-tagName="@tagLink.Tag.Name" style="color:black">@tagLink.Tag.Name</a>
                                    @if (canEdit)
                                    {
                                        <form method="post" asp-page-handler="DeleteTag">
                                            <input type="hidden" value="@Model.JewelryItem.Id" name="JewelryItemId" />
                                            <input type="hidden" value="@tagLink.TagId" name="TagId" />
                                            <button style="background:none; border:none;" onclick="deleteTagFromItem()">
                                                <svg style="pointer-events:none;" width="12" height="12" viewBox="0 0 14 14">
                                                    <path d="M12 3.41L10.59 2 7 5.59 3.41 2 2 3.41 5.59 7 2 10.59 3.41 12 7 8.41 10.59 12 12 10.59 8.41 7z"></path>
                                                </svg>
                                            </button>
                                        </form>
                                    }

                                </li>
                            }
                        }
                    </ul>
                </div>
            </dd>
            <dd class="align-middle">
                <button class="btn btn-primary" type="submit" style="margin-top:10px">Checkout</button>
            </dd>
        </dl>
    </div>
</div>


<div class="text-center" style="margin-top:50px">
    |   <a asp-page="./Items" style="color:black">Back to List</a>  |

    @if (canEdit)
    {
        <a asp-page="./Edit" asp-route-id="@Model.JewelryItem.Id" style="color:black">Edit |</a>
        <a asp-page="./Delete" asp-route-id="@Model.JewelryItem.Id" style="color:black">Delete Item |</a>
    }

</div>